class Config:
    PLAYLIST_REQUEST_TIMEOUT = 5000
    PLAYLIST_UPDATE_MAX_RETRY_COUNT = 10
    PLAYLIST_UPDATE_RETRY_INTERVAL = 3000
    PLAYLIST_UPDATE_INTERVAL = 2000

    FILE_CHUNK_SIZE = 1024
    FILE_REQUEST_TIMEOUT = 10000
    FILE_REQUEST_MAX_RETRY_COUNT = 3
    FILE_REQUEST_RETRY_INTERVAL = 5000
    FILE_DOWNLOAD_MANAGER_MIN_POOL_SIZE = 1
    FILE_DOWNLOAD_MANAGER_MAX_POOL_SIZE = 20

    STREAM_SEGMENT_TITLE_FILTER_REGEX = ["^Amazon\|.*$"]

    UPDATE_TRACK_MAX_RETRY_COUNT = 5
    UPDATE_TRACK_INTERVAL = 120000

    PIPE_TIMEOUT = 10000

    CHANNEL_AUTO_UPDATE_INTERVAL = 180000